// This file was automatically generated.  Do not modify.
/* eslint-disable func-style */
/* eslint-disable require-jsdoc */
/* eslint-disable quote-props */
/* eslint-disable quotes */
/* eslint-disable dot-notation */

function addMsg (Blockly) {

    Object.assign(Blockly.ScratchMsgs.locales["en"],
        {
            "REMOTECONTROLCADA_CATEGORY": "Remoter Control",
            "REMOTECONTROLCADA_SETVIBRATEINTENSITY": "set vibrate intensity %1",
            "REMOTECONTROLCADA_READBUTTONSTATE": "when button %1 is pressed",
            "REMOTECONTROLCADA_BUTTONMENU_REDLEFT": "red left",
            "REMOTECONTROLCADA_BUTTONMENU_REDRIGHT": "red right",
            "REMOTECONTROLCADA_BUTTONMENU_BLACKUP": "black up",
            "REMOTECONTROLCADA_BUTTONMENU_BLACKDOWN": "black down",
            "REMOTECONTROLCADA_BUTTONMENU_BLUELEFT": "blue left",
            "REMOTECONTROLCADA_BUTTONMENU_BLUERIGHT": "blue right",
            "REMOTECONTROLCADA_BUTTONMENU_YELLOWUP": "yellow up",
            "REMOTECONTROLCADA_BUTTONMENU_YELLOWDOWN": "yellow down",
            "REMOTECONTROLCADA_READSWITCHSTATE": "when switch %1 be activated",
            "REMOTECONTROLCADA_SWITCHMENU_RED": "red",
            "REMOTECONTROLCADA_SWITCHMENU_BLACK": "black",
            "REMOTECONTROLCADA_SWITCHMENU_BLUE": "blue",
            "REMOTECONTROLCADA_SWITCHMENU_YELLOW": "yellow",
            "REMOTECONTROLCADA_READANALOGPORT": "read handle %1 analog",
            "REMOTECONTROLCADA_HANDLEMENU_LEFTX": "left x axis",
            "REMOTECONTROLCADA_HANDLEMENU_LEFTY": "left y axis",
            "REMOTECONTROLCADA_HANDLEMENU_RIGHTX": "right x axis",
            "REMOTECONTROLCADA_HANDLEMENU_RIGHTY": "right y axis",
            "REMOTECONTROLCADA_READEQUIPACCELER": "read device value of %1",
            "REMOTECONTROLCADA_ACCELERMENU_X": "x acc",
            "REMOTECONTROLCADA_ACCELERMENU_Y": "y acc",
            "REMOTECONTROLCADA_ACCELERMENU_Z": "z acc",
            "REMOTECONTROLCADA_ACCELERMENU_BAT": "bat",
            "REMOTECONTROLCADA_READEQUIPSTATE": "when device state is %1",
            "REMOTECONTROLCADA_DEVICESTATEMENU_FLAT": "flat",
            "REMOTECONTROLCADA_DEVICESTATEMENU_TILT": "tilt",
            "REMOTECONTROLCADA_DEVICESTATEMENU_FORWARD": "forward",
            "REMOTECONTROLCADA_DEVICESTATEMENU_BACKWARD": "backward",
            "REMOTECONTROLCADA_DEVICESTATEMENU_LEFT": "left",
            "REMOTECONTROLCADA_DEVICESTATEMENU_RIGHT": "right",
            "REMOTECONTROLCADA_DEVICESTATEMENU_SHAKING": "shaking",
            "REMOTECONTROLCADA_DEVICESTATEMENU_DISPLACEMENT": "displacement"
        }
    );

    Object.assign(Blockly.ScratchMsgs.locales["zh-cn"],
        {
            "REMOTECONTROLCADA_CATEGORY": "遥控",
            "REMOTECONTROLCADA_SETVIBRATEINTENSITY": "设置震动强度 %1",
            "REMOTECONTROLCADA_READBUTTONSTATE": "当按钮 %1 被按下",
            "REMOTECONTROLCADA_BUTTONMENU_REDLEFT": "红色左",
            "REMOTECONTROLCADA_BUTTONMENU_REDRIGHT": "红色右",
            "REMOTECONTROLCADA_BUTTONMENU_BLACKUP": "黑色上",
            "REMOTECONTROLCADA_BUTTONMENU_BLACKDOWN": "黑色下",
            "REMOTECONTROLCADA_BUTTONMENU_BLUELEFT": "蓝色左",
            "REMOTECONTROLCADA_BUTTONMENU_BLUERIGHT": "蓝色右",
            "REMOTECONTROLCADA_BUTTONMENU_YELLOWUP": "黄色上",
            "REMOTECONTROLCADA_BUTTONMENU_YELLOWDOWN": "黄色下",
            "REMOTECONTROLCADA_READSWITCHSTATE": "当开关 %1 被激活",
            "REMOTECONTROLCADA_SWITCHMENU_RED": "红色",
            "REMOTECONTROLCADA_SWITCHMENU_BLACK": "黑色",
            "REMOTECONTROLCADA_SWITCHMENU_BLUE": "蓝色",
            "REMOTECONTROLCADA_SWITCHMENU_YELLOW": "黄色",
            "REMOTECONTROLCADA_READANALOGPORT": "读取手柄 %1 模拟量",
            "REMOTECONTROLCADA_HANDLEMENU_LEFTX": "左手柄X轴",
            "REMOTECONTROLCADA_HANDLEMENU_LEFTY": "左手柄Y轴",
            "REMOTECONTROLCADA_HANDLEMENU_RIGHTX": "右手柄X轴",
            "REMOTECONTROLCADA_HANDLEMENU_RIGHTY": "右手柄Y轴",
            "REMOTECONTROLCADA_READEQUIPACCELER": "读取设备 %1 的数值",
            "REMOTECONTROLCADA_ACCELERMENU_X": "加速度X",
            "REMOTECONTROLCADA_ACCELERMENU_Y": "加速度Y",
            "REMOTECONTROLCADA_ACCELERMENU_Z": "加速度Z",
            "REMOTECONTROLCADA_ACCELERMENU_BAT": "电量",
            "REMOTECONTROLCADA_READEQUIPSTATE": "当设备状态为 %1",
            "REMOTECONTROLCADA_DEVICESTATEMENU_FLAT": "平放",
            "REMOTECONTROLCADA_DEVICESTATEMENU_TILT": "倾斜",
            "REMOTECONTROLCADA_DEVICESTATEMENU_FORWARD": "前倾",
            "REMOTECONTROLCADA_DEVICESTATEMENU_BACKWARD": "后倾",
            "REMOTECONTROLCADA_DEVICESTATEMENU_LEFT": "左倾",
            "REMOTECONTROLCADA_DEVICESTATEMENU_RIGHT": "右倾",
            "REMOTECONTROLCADA_DEVICESTATEMENU_SHAKING": "晃动",
            "REMOTECONTROLCADA_DEVICESTATEMENU_DISPLACEMENT": "位移"
        }
    );

    Object.assign(Blockly.ScratchMsgs.locales["zh-tw"],
        {
            "REMOTECONTROLCADA_CATEGORY": "遙控",
            "REMOTECONTROLCADA_SETVIBRATEINTENSITY": "設定震動強度 %1",
            "REMOTECONTROLCADA_READBUTTONSTATE": "當按鈕 %1 被按下",
            "REMOTECONTROLCADA_BUTTONMENU_REDLEFT": "紅色左",
            "REMOTECONTROLCADA_BUTTONMENU_REDRIGHT": "紅色右",
            "REMOTECONTROLCADA_BUTTONMENU_BLACKUP": "黑色上",
            "REMOTECONTROLCADA_BUTTONMENU_BLACKDOWN": "黑色下",
            "REMOTECONTROLCADA_BUTTONMENU_BLUELEFT": "藍色左",
            "REMOTECONTROLCADA_BUTTONMENU_BLUERIGHT": "藍色右",
            "REMOTECONTROLCADA_BUTTONMENU_YELLOWUP": "黃色上",
            "REMOTECONTROLCADA_BUTTONMENU_YELLOWDOWN": "黃色下",
            "REMOTECONTROLCADA_READSWITCHSTATE": "當開關 %1 被激活",
            "REMOTECONTROLCADA_SWITCHMENU_RED": "紅色",
            "REMOTECONTROLCADA_SWITCHMENU_BLACK": "黑色",
            "REMOTECONTROLCADA_SWITCHMENU_BLUE": "藍色",
            "REMOTECONTROLCADA_SWITCHMENU_YELLOW": "黃色",
            "REMOTECONTROLCADA_READANALOGPORT": "讀取手把 %1 類比量",
            "REMOTECONTROLCADA_HANDLEMENU_LEFTX": "左手柄X軸",
            "REMOTECONTROLCADA_HANDLEMENU_LEFTY": "左手柄Y軸",
            "REMOTECONTROLCADA_HANDLEMENU_RIGHTX": "右手柄X軸",
            "REMOTECONTROLCADA_HANDLEMENU_RIGHTY": "右手柄Y軸",
            "REMOTECONTROLCADA_READEQUIPACCELER": "讀取設備 %1 的數值",
            "REMOTECONTROLCADA_ACCELERMENU_X": "加速度X",
            "REMOTECONTROLCADA_ACCELERMENU_Y": "加速度Y",
            "REMOTECONTROLCADA_ACCELERMENU_Z": "加速度Z",
            "REMOTECONTROLCADA_ACCELERMENU_BAT": "電量",
            "REMOTECONTROLCADA_READEQUIPSTATE": "當設備狀態為 %1",
            "REMOTECONTROLCADA_DEVICESTATEMENU_FLAT": "平放",
            "REMOTECONTROLCADA_DEVICESTATEMENU_TILT": "傾斜",
            "REMOTECONTROLCADA_DEVICESTATEMENU_FORWARD": "前傾",
            "REMOTECONTROLCADA_DEVICESTATEMENU_BACKWARD": "後傾",
            "REMOTECONTROLCADA_DEVICESTATEMENU_LEFT": "左傾",
            "REMOTECONTROLCADA_DEVICESTATEMENU_RIGHT": "右傾",
            "REMOTECONTROLCADA_DEVICESTATEMENU_SHAKING": "晃動",
            "REMOTECONTROLCADA_DEVICESTATEMENU_DISPLACEMENT": "位移"
        }
    );

    return Blockly;
}

exports = addMsg;
// End of combined translations
