// This file was automatically generated.  Do not modify.
/* eslint-disable func-style */
/* eslint-disable require-jsdoc */
/* eslint-disable quote-props */
/* eslint-disable quotes */
/* eslint-disable dot-notation */

function addMsg (Blockly) {

    Object.assign(Blockly.ScratchMsgs.locales["en"],
        {
            "LINEFINDERCADA_CATEGORY_CONFIG": "Config",
            "LINEFINDERCADA_CATEGORY_LINEFINDER": "Line Finder",
            "LINEFINDERCADA_CATEGORY_RUN": "Drive",
            "LINEFINDERCADA_CATEGORY_ACTION": "Action",
            "LINEFINDERCADA_SETDIAGNOSTICFUNCTIONS": "set diagnostic functions %",
            "LINEFINDERCADA_OFF": "OFF",
            "LINEFINDERCADA_SETTIMER": "set timer line %1 over %2 turn %3",
            "LINEFINDERCADA_SETSPEED": "set speed line %1 clean %2 turn %3",
            "LINEFINDERCADA_SETSPEEDADJ": "adjust %1 left speed to %2 right speed to %3", 
            "LINEFINDERCADA_SETSENSORTHRESHOLD": "set line following sensors threshold values left (70) right (70)",
            "LINEFINDERCADA_MECHDATA": "set wheel diameter %1 wheel base %2 spacing %3 line width %4 reduction ratio %5",
            "LINEFINDERCADA_SETTURNEFFICIENCY": "set efficiency straight %1 turning %2",
            "LINEFINDERCADA_ACTIONSPEEDUPDATE": "update dirve speed %1",
            "LINEFINDERCADA_SETLOOPJUMP": "from step %1 loop %2 times",
            "LINEFINDERCADA_SETSERVOPOS": "set servo1 pos %1 servo2 pos %2",
            "LINEFINDERCADA_ACTIONLOOPJUMP": "jump to step %1 %2 times",
            "LINEFINDERCADA_ACTIONLINEFINDERMODE": "switch line finder mode %1",
            "LINEFINDERCADA_SETPORTCONNECTION": "set port %1 connect %2",
            "LINEFINDERCADA_ULTRASONICWAVE": "ultrasonic wave",
            "LINEFINDERCADA_SPEAKER": "speaker",
            "LINEFINDERCADA_SERVO": "servo",
            "LINEFINDERCADA_INDICATORLIGHT": "indicator light",
            "LINEFINDERCADA_TASK": "task %1",
            "LINEFINDERCADA_RUNTASK": "run task %1",
            "LINEFINDERCADA_STEPACTION": "step %1 run %2",
            "LINEFINDERCADA_NONE": "none",
            "LINEFINDERCADA_ACTIONSTARTBYPASS": "exit base",
            "LINEFINDERCADA_ACTIONCROSSBYPASS": "cross the crossroads",
            "LINEFINDERCADA_ACTIONCROSSTURNLEFT": "turn left at crossroads",
            "LINEFINDERCADA_ACTIONCROSSTURNRIGHT": "turn right at crossroads",
            "LINEFINDERCADA_ACTIONCROSSRETURNLEFT": "turn left and make a U-turn at crossroads",
            "LINEFINDERCADA_ACTIONCROSSRETURNRIGHT": "turn right and make a U-turn at crossroads",
            "LINEFINDERCADA_ACTIONSIDEBYPASS": "cross the T-shaped road %1",
            "LINEFINDERCADA_NORMAL": "normal",
            "LINEFINDERCADA_TURNLEFTT": "left T",
            "LINEFINDERCADA_TURNRIGHTT": "right T",
            "LINEFINDERCADA_TURNLEFT": "turn left",
            "LINEFINDERCADA_TURNRIGHT": "turn right",
            "LINEFINDERCADA_FORWARD": "go forward",
            "LINEFINDERCADA_BACKWARD": "go backward",
            "LINEFINDERCADA_ACTIONSIDETURNLEFT": "turn left at the T-junction",
            "LINEFINDERCADA_ACTIONSIDETURNRIGHT": "turn right at the T-junction",
            "LINEFINDERCADA_ACTIONSIDERETURNLEFT": "turn left at the T-intersection and make a U-turn",
            "LINEFINDERCADA_ACTIONSIDERETURNRIGHT": "turn right at the T-intersection and make a U-turn",
            "LINEFINDERCADA_ACTIONSTOPAFTERTIME": "stop after %1 ms of line patrol",
            "LINEFINDERCADA_ACTIONSTOPAFTERDIST": "stop after %1 mm of line patrol",
            "LINEFINDERCADA_ACTIONSTOPAFTERTIMESPEED": "follow the line at %1 speed and stop after %2 ms",
            "LINEFINDERCADA_ACTIONSTOPAFTERDISTSPEED": "follow the line at %1 speed and stop after %2 mm",
            "LINEFINDERCADA_ACTIONGOFORWARDTIME":"go forward %1 ms",
            "LINEFINDERCADA_ACTIONGOFORWARDDIST":"go forward %1 mm",
            "LINEFINDERCADA_ACTIONGOFORWARDTIMESPEED":"go forward %1 ms at %2 speed",
            "LINEFINDERCADA_ACTIONGOFORWARDDISTSPEED":"go forward %1 mm at %1 speed",
            "LINEFINDERCADA_ACTIONGOBACKWARDTIME":"go backward %1 ms",
            "LINEFINDERCADA_ACTIONGOBACKWARDDIST":"go backward %1 mm",
            "LINEFINDERCADA_ACTIONGOBACKWARDTIMESPEED":"go backward %1 ms at %2 speed",
            "LINEFINDERCADA_ACTIONGOBACKWARDDISTSPEED":"go backward %1 mm at %1 speed",
            "LINEFINDERCADA_ACTIONGOLEFTTIME":"turn left %1 ms",
            "LINEFINDERCADA_ACTIONGOLEFTANGLE":"turn left %1 degree",
            "LINEFINDERCADA_ACTIONGOLEFTTIMESPEED":"turn left %1 ms at %2 speed",
            "LINEFINDERCADA_ACTIONGOLEFTANGLESPEED":"turn left %1 degree at %2 speed",
            "LINEFINDERCADA_ACTIONGORIGHTTIME":"turn right %1 ms",
            "LINEFINDERCADA_ACTIONGORIGHTANGLE":"turn right %1 degree",
            "LINEFINDERCADA_ACTIONGORIGHTTIMESPEED":"turn right %1 ms at %2 speed",
            "LINEFINDERCADA_ACTIONGORIGHTANGLESPEED": "turn right %1 degree at %2 speed",
            "LINEFINDERCADA_ACTIONWAIT": "wait %1s",
            "LINEFINDERCADA_ACTIONWAITACK": "wait %1 triger",
            "LINEFINDERCADA_ACTIONMULTIPORTACT": "port %1 %2 output %3 for %4 ms",
            "LINEFINDERCADA_ACTIONGOFORWARD": "keep go forward",
            "LINEFINDERCADA_ACTIONGOBACKWARD": "keep go backward",
            "LINEFINDERCADA_ACTIONGOLEFT": "keep go left",
            "LINEFINDERCADA_ACTIONGORIGHT": "keep go right"
        }
    );

    Object.assign(Blockly.ScratchMsgs.locales["zh-cn"],
        {
            "LINEFINDERCADA_CATEGORY_CONFIG": "配置",
            "LINEFINDERCADA_CATEGORY_LINEFINDER": "巡线",
            "LINEFINDERCADA_CATEGORY_RUN": "行驶",
            "LINEFINDERCADA_CATEGORY_ACTION": "动作",
            "LINEFINDERCADA_SETDIAGNOSTICFUNCTIONS": "设定诊断功能 %1",
            "LINEFINDERCADA_OFF": "关闭",
            "LINEFINDERCADA_SETTIMER": "设定计时 巡线 %1 过线 %2 转弯 %3",
            "LINEFINDERCADA_SETSPEED": "设定速度 行驶 %1 倾斜 %2 转弯 %3",
            "LINEFINDERCADA_SETSPEEDADJ": "修正 %1 左轮速度 %2 右轮速度 %3", 
            "LINEFINDERCADA_SETSENSORTHRESHOLD": "设定巡线传感器阈值 左 %1 右 %2",
            "LINEFINDERCADA_MECHDATA": "设定轮径 %1 轮距 %2 间距 %3 线宽 %4 减速比 %5",
            "LINEFINDERCADA_SETTURNEFFICIENCY": "设定效率 直行 %1 转向 %2",
            "LINEFINDERCADA_ACTIONSPEEDUPDATE": "行驶速度更新 %1",
            "LINEFINDERCADA_SETLOOPJUMP": "从步骤 %1 开始循环 %2 次",
            "LINEFINDERCADA_SETSERVOPOS": "设置舵机1 %1 设置舵机2 %2",
            "LINEFINDERCADA_ACTIONLOOPJUMP": "跳到步骤 %1 循环 %2 次",
            "LINEFINDERCADA_ACTIONLINEFINDERMODE": "切换巡线模式为 %1",
            "LINEFINDERCADA_SETPORTCONNECTION": "设置端口 %1 连接 %2",
            "LINEFINDERCADA_ULTRASONICWAVE": "超声波",
            "LINEFINDERCADA_SPEAKER": "喇叭",
            "LINEFINDERCADA_SERVO": "舵机",
            "LINEFINDERCADA_INDICATORLIGHT": "指示灯",
            "LINEFINDERCADA_NONE": "无",
            "LINEFINDERCADA_TASK": "任务 %1",
            "LINEFINDERCADA_RUNTASK": "执行任务 %1",
            "LINEFINDERCADA_STEPACTION": "步骤 %1 执行 %2",
            "LINEFINDERCADA_ACTIONSTARTBYPASS": "驶出基地",
            "LINEFINDERCADA_ACTIONCROSSBYPASS": "穿过十字路口",
            "LINEFINDERCADA_ACTIONCROSSTURNLEFT": "十字路口左转",
            "LINEFINDERCADA_ACTIONCROSSTURNRIGHT": "十字路口右转",
            "LINEFINDERCADA_ACTIONCROSSRETURNLEFT": "十字路口左转掉头",
            "LINEFINDERCADA_ACTIONCROSSRETURNRIGHT": "十字路口右转掉头",
            "LINEFINDERCADA_ACTIONSIDEBYPASS": "穿过丁字路 %1",
            "LINEFINDERCADA_NORMAL": "正常",
            "LINEFINDERCADA_TURNLEFTT": "左T",
            "LINEFINDERCADA_TURNRIGHTT": "右T",
            "LINEFINDERCADA_TURNLEFT": "左转",
            "LINEFINDERCADA_TURNRIGHT": "右转",
            "LINEFINDERCADA_FORWARD": "前进",
            "LINEFINDERCADA_BACKWARD": "后退",
            "LINEFINDERCADA_ACTIONSIDETURNLEFT": "丁字路口左转",
            "LINEFINDERCADA_ACTIONSIDETURNRIGHT": "丁字路口右转",
            "LINEFINDERCADA_ACTIONSIDERETURNLEFT": "丁字路口左转掉头",
            "LINEFINDERCADA_ACTIONSIDERETURNRIGHT": "丁字路口右转掉头",
            "LINEFINDERCADA_ACTIONSTOPAFTERTIME": "巡线 %1 ms 后停车",
            "LINEFINDERCADA_ACTIONSTOPAFTERDIST": "巡线 %1 mm 后停车",
            "LINEFINDERCADA_ACTIONSTOPAFTERTIMESPEED": "以速度 %2 巡线 %1 ms 后停车",
            "LINEFINDERCADA_ACTIONSTOPAFTERDISTSPEED": "以速度 %2 巡线 %1 mm 后停车",
            "LINEFINDERCADA_ACTIONGOFORWARDTIME":"前进 %1 ms",
            "LINEFINDERCADA_ACTIONGOFORWARDDIST":"前进 %1 mm",
            "LINEFINDERCADA_ACTIONGOFORWARDTIMESPEED":"以速度 %2 前进 %1 ms",
            "LINEFINDERCADA_ACTIONGOFORWARDDISTSPEED":"以速度 %2 前进 %1 mm",
            "LINEFINDERCADA_ACTIONGOBACKWARDTIME":"后退 %1 ms",
            "LINEFINDERCADA_ACTIONGOBACKWARDDIST":"后退 %1 mm",
            "LINEFINDERCADA_ACTIONGOBACKWARDTIMESPEED":"以速度 %2 后退 %1 ms",
            "LINEFINDERCADA_ACTIONGOBACKWARDDISTSPEED":"以速度 %2 后退 %1 mm",
            "LINEFINDERCADA_ACTIONGOLEFTTIME":"左转 %1 ms",
            "LINEFINDERCADA_ACTIONGOLEFTANGLE":"左转 %1 度",
            "LINEFINDERCADA_ACTIONGOLEFTTIMESPEED":"以速度 %2 左转 %1 ms",
            "LINEFINDERCADA_ACTIONGOLEFTANGLESPEED":"以速度 %2 左转 %1 度",
            "LINEFINDERCADA_ACTIONGORIGHTTIME":"右转 %1 ms",
            "LINEFINDERCADA_ACTIONGORIGHTANGLE":"右转 %1 度",
            "LINEFINDERCADA_ACTIONGORIGHTTIMESPEED":"以速度 %2 右转 %1 ms",
            "LINEFINDERCADA_ACTIONGORIGHTANGLESPEED": "以速度 %2 右转 %1 度",
            "LINEFINDERCADA_ACTIONWAIT": "待机 %1 ms",
            "LINEFINDERCADA_ACTIONWAITACK": "等待 %1 触发",
            "LINEFINDERCADA_ACTIONMULTIPORTACT": "端口 %1 的 %2 输出 %3 共 %4 ms",
            "LINEFINDERCADA_ACTIONGOFORWARD": "继续前进",
            "LINEFINDERCADA_ACTIONGOBACKWARD": "继续后退",
            "LINEFINDERCADA_ACTIONGOLEFT": "继续左转",
            "LINEFINDERCADA_ACTIONGORIGHT": "继续右转"
        }
    );

    Object.assign(Blockly.ScratchMsgs.locales["zh-tw"],
        {
            "LINEFINDERCADA_CATEGORY_CONFIG": "配置",
            "LINEFINDERCADA_CATEGORY_LINEFINDER": "巡線",
            "LINEFINDERCADA_CATEGORY_RUN": "行駛",
            "LINEFINDERCADA_CATEGORY_ACTION": "動作",
            "LINEFINDERCADA_SETDIAGNOSTICFUNCTIONS": "設定診斷功能 %1",
            "LINEFINDERCADA_OFF": "關閉",
            "LINEFINDERCADA_SETTIMER": "設定計時 巡線 %1 過線 %2 轉彎 %3",
            "LINEFINDERCADA_SETSPEED": "設定速度 行駛 %1 傾斜 %2 轉彎 %3",
            "LINEFINDERCADA_SETSPEEDADJ": "修正 %1 左輪速度 %2 右輪速度 %3",
            "LINEFINDERCADA_SETSENSORTHRESHOLD": "設定巡線感知器閾值左 %1 右 %2",
            "LINEFINDERCADA_MECHDATA": "設定輪徑 %1 輪距 %2 間距 %3 線寬 %4 減速比 %5",
            "LINEFINDERCADA_SETTURNEFFICIENCY": "設定效率 直行 %1 轉向 %2",
            "LINEFINDERCADA_SETPORTCONNECTION": "設定連接埠 %1 連接 %2",
            "LINEFINDERCADA_ACTIONSPEEDUPDATE": "行驶速度更新 %1",
            "LINEFINDERCADA_SETLOOPJUMP": "从步骤 %1 开始循环 %2 次",
            "LINEFINDERCADA_SETSERVOPOS": "设置舵机1 %1 设置舵机2 %2",
            "LINEFINDERCADA_ACTIONLOOPJUMP": "跳到步骤 %1 循环 %2 次",
            "LINEFINDERCADA_ACTIONLINEFINDERMODE": "切换巡线模式为 %1",
            "LINEFINDERCADA_ULTRASONICWAVE": "超音波",
            "LINEFINDERCADA_SPEAKER": "喇叭",
            "LINEFINDERCADA_SERVO": "舵機",
            "LINEFINDERCADA_INDICATORLIGHT": "指示燈",
            "LINEFINDERCADA_NONE": "無",
            "LINEFINDERCADA_TASK": "任務 %1",
            "LINEFINDERCADA_RUNTASK": "執行任務 %1",
            "LINEFINDERCADA_STEPACTION": "步驟 %1 執行 %2",
            "LINEFINDERCADA_ACTIONSTARTBYPASS": "駛出基地",
            "LINEFINDERCADA_ACTIONCROSSBYPASS": "穿越十字路口",
            "LINEFINDERCADA_ACTIONCROSSTURNLEFT": "十字路口左轉",
            "LINEFINDERCADA_ACTIONCROSSTURNRIGHT": "十字路口右轉",
            "LINEFINDERCADA_ACTIONCROSSRETURNLEFT": "十字路口左轉掉頭",
            "LINEFINDERCADA_ACTIONCROSSRETURNRIGHT": "十字路口右轉掉頭",
            "LINEFINDERCADA_ACTIONSIDEBYPASS": "穿過丁字路 %1",
            "LINEFINDERCADA_NORMAL": "正常",
            "LINEFINDERCADA_TURNLEFTT": "左T",
            "LINEFINDERCADA_TURNRIGHTT": "右T",
            "LINEFINDERCADA_TURNLEFT": "左轉",
            "LINEFINDERCADA_TURNRIGHT": "右轉",
            "LINEFINDERCADA_FORWARD": "前進",
             "LINEFINDERCADA_BACKWARD": "後退",
            "LINEFINDERCADA_ACTIONSIDETURNLEFT": "丁字路口左轉",
            "LINEFINDERCADA_ACTIONSIDETURNRIGHT": "丁字路口右轉",
            "LINEFINDERCADA_ACTIONSIDERETURNLEFT": "丁字路口左轉掉頭",
            "LINEFINDERCADA_ACTIONSIDERETURNRIGHT": "丁字路口右轉掉頭",
            "LINEFINDERCADA_ACTIONSTOPAFTERTIME": "巡線 %1 ms 後停車",
            "LINEFINDERCADA_ACTIONSTOPAFTERDIST": "巡線 %1 mm 後停車",
            "LINEFINDERCADA_ACTIONSTOPAFTERTIMESPEED": "以速度 %2 巡線 %1 ms 後停車",
            "LINEFINDERCADA_ACTIONSTOPAFTERDISTSPEED": "以速度 %2 巡線 %1 mm 後停車",
            "LINEFINDERCADA_ACTIONGOFORWARDTIME":"前進 %1 ms",
            "LINEFINDERCADA_ACTIONGOFORWARDDIST":"前進 %1 mm",
            "LINEFINDERCADA_ACTIONGOFORWARDTIMESPEED":"以速度 %2 前進 %1 ms",
            "LINEFINDERCADA_ACTIONGOFORWARDDISTSPEED":"以速度 %2 前進 %1 mm",
            "LINEFINDERCADA_ACTIONGOBACKWARDTIME":"後退 %1 ms",
            "LINEFINDERCADA_ACTIONGOBACKWARDDIST":"後退 %1 mm ",
            "LINEFINDERCADA_ACTIONGOBACKWARDTIMESPEED":"以速度 %2 後退 %1 ms",
            "LINEFINDERCADA_ACTIONGOBACKWARDDISTSPEED":"以速度 %2 後退 %1 mm",
            "LINEFINDERCADA_ACTIONGOLEFTTIME":"左轉 %1 ms",
            "LINEFINDERCADA_ACTIONGOLEFTANGLE":"左轉 %1 度",
            "LINEFINDERCADA_ACTIONGOLEFTTIMESPEED":"以速度 %2 左轉 %1 ms",
            "LINEFINDERCADA_ACTIONGOLEFTANGLESPEED":"以速度 %2 左轉 %1 度",
            "LINEFINDERCADA_ACTIONGORIGHTTIME":"右轉 %1 ms",
            "LINEFINDERCADA_ACTIONGORIGHTANGLE":"右轉 %1 度",
            "LINEFINDERCADA_ACTIONGORIGHTTIMESPEED":"以速度 %2 右轉 %1 ms ",
            "LINEFINDERCADA_ACTIONGORIGHTANGLESPEED": "以速度 %2右轉 %1 度",
            "LINEFINDERCADA_ACTIONWAIT": "待機 %1 ms",
            "LINEFINDERCADA_ACTIONWAITACK": "等待 %1 觸發",
            "LINEFINDERCADA_ACTIONMULTIPORTACT": "連接埠 %1 的 %2 輸出 %3 共 %4 ms",
            "LINEFINDERCADA_ACTIONGOFORWARD": "繼續前進",
            "LINEFINDERCADA_ACTIONGOBACKWARD": "繼續後退",
            "LINEFINDERCADA_ACTIONGOLEFT": "繼續左轉",
            "LINEFINDERCADA_ACTIONGORIGHT": "繼續往右轉"
        }
    );

    return Blockly;
}

exports = addMsg;
// End of combined translations
