module.exports = [
    // Buid-in device
    'magicLogicBLE01',
    'magicLogicBLE02',
    'magicLogicBLE04',
    'magicLogicBLE05_magicLogicBLE05',
    'magicLogicBLE06',
    'arduinoUno',
    'arduinoNano',
    'arduinoLeonardo',
    'arduinoMega2560',
    'esp32',
    'arduinoEsp32',
    'microPythonEsp32',
    'esp8266NodeMCU',
    'arduinoEsp8266NodeMCU',
    'microPythonEsp8266NodeMCU',
    'microbit',
    'microbitV2',
    'k210MaixDock',
    'arduinoK210MaixDock',
    'microPythonK210MaixDock',
    'k210Maixduino',
    'arduinoK210Maixduino',
    'microPythonK210Maixduino',
    'makeyMakey'
];
